# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chaos Cooperative
email: chaoscooperative@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

nav:
 #text included on the top left of the navbar which acts as a home button
 brand_name: Chaos Cooperative

#Include site analytics
analytics:
 google:
  analytics_id: UA-47343457-1

#leave usernames blank to exclude social features
social:
 twitter:
  username: chaoscooperativ
 youtube:
  username: UCptUr93MbHWsX1xcfLl_NYw
  #1 to auto play video or 0 to load paused
  auto_play_video: 1
 facebook:
  username: Chaos Cooperative
 google+:
  username: Chaos Cooperative


 
# Build settings
markdown: kramdown
